package simcli.entities.actors;

import simcli.entities.models.Gender;
import simcli.entities.models.Job;
import simcli.utils.GameRandom;

/**
 * A non-playable character (NPC) Sim that inhabits the park.
 *
 * <p>NPCs are generated by {@link simcli.entities.managers.NPCManager}
 * with random names, ages, genders, and jobs. They can be befriended
 * and eventually married into the player's household.</p>
 */
public class NPCSim extends Sim {

    /**
     * Constructs a new NPC with a randomly assigned gender.
     *
     * @param name the display name of this NPC.
     * @param age  the starting age of this NPC.
     */
    public NPCSim(String name, int age) {
        super(name, age, GameRandom.RANDOM.nextBoolean() ? Gender.MALE : Gender.FEMALE);
    }

    /**
     * Constructs a new NPC with explicit gender and career.
     *
     * @param name   the display name of this NPC.
     * @param age    the starting age of this NPC.
     * @param gender the gender of this NPC.
     * @param job    the career assigned to this NPC.
     */
    public NPCSim(String name, int age, Gender gender, Job job) {
        super(name, age, gender, job);
    }
}
